### ISSUE TITLE
Add information about Singularity login files and prompts

### ISSUE THREAD

**Issue by aperloff** [awesome-workshop/docker-singularity-hats#4]
Additions recommended by @kpedro88

Information to add:
- Singularity will call the user's `.bashrc` file when starting a container
  - Some environment settings are overridden by default (https://sylabs.io/guides/3.7/user-guide/environment_and_metadata.html)
- To set a display prompt for the Singularity container put the following in a `.bashrc` file:
```bash
export SINGULARITYENV_PS1="..."
```
- To detect if you're in a singularity container do:
```bash
if [ -n "$SINGULARITY_CONTAINER" ]; then
    <add code here>
fi
```

**Comment by kpedro88** [comment]
Addressed by #5
